; =============================================================================
; reu_advanced.asm - REU status display, fill, save-to-disk, random fill, getin_wait
; Related: reu_core.asm (detection and basic operations)
; =============================================================================

; =============================================================================
; do_show_reu_status - display REU presence and size
; =============================================================================
do_show_reu_status:
        lda #$0d
        jsr chrout
        
        lda #<reu_status_msg
        ldy #>reu_status_msg
        jsr print_string
        
        ; Run REU detection now
        lda #<reu_detecting_msg
        ldy #>reu_detecting_msg
        jsr print_string
        
        jsr detect_reu
        
        ; Check result
        lda reu_present
        bne @show_present
        
        lda #<reu_not_present_msg
        ldy #>reu_not_present_msg
        jsr print_string
        jmp @done
        
@show_present:
        lda #<reu_present_msg
        ldy #>reu_present_msg
        jsr print_string
        
        ; display size in decimal KB
        lda #<reu_size_is_msg
        ldy #>reu_size_is_msg
        jsr print_string
        
        ; print reu_size_kb as decimal
        lda reu_size_kb
        sta zp_temp
        lda reu_size_kb+1
        sta zp_temp+1
        jsr print_decimal_word
        
        lda #<reu_kb_suffix
        ldy #>reu_kb_suffix
        jsr print_string
        
        ; Ask if user wants to fill the REU
        lda #<reu_fill_prompt
        ldy #>reu_fill_prompt
        jsr print_string
        
        jsr getin_wait
        cmp #'N'
        beq @done
        cmp #'n'
        beq @done
        ; Enter or Y = yes, continue to ask zero or random
        
        ; Ask zero or random fill
        lda #<reu_fill_type_prompt
        ldy #>reu_fill_type_prompt
        jsr print_string
        
        jsr getin_wait
        cmp #'R'
        beq @random_fill
        cmp #'r'
        beq @random_fill
        ; Enter or 0 = zero fill
        
        ; Zero-fill the REU
        lda #0
        sta reu_fill_random
        jsr fill_reu
        jmp @done
        
@random_fill:
        lda #1
        sta reu_fill_random
        jsr fill_reu
        
@done:
        lda #<instructions_msg
        ldy #>instructions_msg
        jsr print_string
        rts

; =============================================================================
; =============================================================================
; fill_reu - fill entire REU with zeros or random, showing progress
; reu_fill_random: 0=zeros, 1=random
; Exit if user presses space bar
;
; Zero fill optimization: uses REU "fix C64 address" mode ($DF0A bit 7)
; to DMA a single zero byte across an entire 64KB bank in one operation.
; This is ~256x faster than the per-page approach since the REC reads
; the same C64 byte repeatedly while incrementing the REU address.
; DMA rate is ~1 byte/cycle = ~65ms per 64KB bank.
;
; Random fill: must use per-page stashes since each page needs unique
; random data generated by the PRNG.
; =============================================================================
fill_reu:
        ; Show appropriate message
        lda reu_fill_random
        beq @zero_msg
        lda #<reu_random_msg
        ldy #>reu_random_msg
        jmp @print_msg
@zero_msg:
        lda #<reu_zeroing_msg
        ldy #>reu_zeroing_msg
@print_msg:
        jsr print_string
        
        ; Do the actual fill
        jsr refill_reu_core
        bcs @aborted            ; carry set = user aborted
        
        ; Fill complete
        lda #$0d
        jsr chrout
        lda #<reu_fill_done_msg
        ldy #>reu_fill_done_msg
        jsr print_string
        
        ; Only offer save for random fill
        lda reu_fill_random
        beq @fill_exit
        jsr offer_save_reu_to_disk
        
@fill_exit:
        ; Restore address control to normal (increment both)
        lda #0
        sta $df0a
        rts
        
@aborted:
        lda #$0d
        jsr chrout
        lda #<reu_aborted_msg
        ldy #>reu_aborted_msg
        jsr print_string
        ; Restore address control
        lda #0
        sta $df0a
        rts

; =============================================================================
; refill_reu_core - raw REU fill without UI prompts or save offer
; Used by fill_reu (full UI) and by the multi-pass disk writer (silent)
; Returns: carry clear = completed, carry set = user aborted (space bar)
; =============================================================================
refill_reu_core:
        ; Initialize counters
        lda #0
        sta reu_fill_bank
        sta reu_fill_addr_hi
        sta reu_kb_counter
        sta reu_kb_counter+1
        
        ; reu_banks = (number of 64KB banks) - 1
        ; For 128KB: reu_banks = 1 (banks 0-1)
        ; For 512KB: reu_banks = 7 (banks 0-7)
        ; For 16MB:  reu_banks = 0 (meaning 256, banks 0-255, wraps)
        ; We fill banks 0 through reu_banks inclusive.
        ; Completion: after incrementing fill_bank, if it equals
        ; (reu_banks + 1) we're done. For the 256-bank case,
        ; reu_banks + 1 wraps to 0, and fill_bank also wraps to 0
        ; after bank 255, so the comparison still works.
        
        ; Branch based on fill mode
        lda reu_fill_random
        bne @random_fill_path
        jmp @fast_zero_fill
        
; ---- Random fill path (per-page stash, same as before) ----
@random_fill_path:
        jsr prepare_fill_buffer
        
@rand_fill_loop:
        ; Check for space bar to abort
        jsr getin
        cmp #$20
        bne @rand_not_aborted
        jmp @aborted
@rand_not_aborted:
        
        ; Refill buffer with new random data each page
        jsr prepare_fill_buffer
        
        ; Stash 256-byte buffer to REU
        lda #<reu_zero_buffer
        sta $df02
        lda #>reu_zero_buffer
        sta $df03
        
        lda #0
        sta $df04               ; REU address low
        lda reu_fill_addr_hi
        sta $df05               ; REU address high
        lda reu_fill_bank
        sta $df06               ; REU bank
        
        lda #0
        sta $df07               ; length low (0 = 256)
        lda #1
        sta $df08               ; length high
        lda #0
        sta $df0a               ; increment both addresses
        
        lda #$90                ; stash with execute
        sta $df01
        
        ; Show progress every 1KB (4 x 256 bytes)
        lda reu_fill_addr_hi
        and #$03
        cmp #$03
        bne @rand_advance
        
        ; Increment KB counter
        inc reu_kb_counter
        bne +
        inc reu_kb_counter+1
+       jsr show_fill_progress
        
@rand_advance:
        inc reu_fill_addr_hi
        beq @rand_bank_wrap
        jmp @rand_fill_loop
        
@rand_bank_wrap:
        inc reu_fill_bank
        beq @complete           ; wrapped 255->0: all 256 banks done (16MB)
        
        ; For reu_banks=0 (256 banks), only the wrap above terminates
        lda reu_banks
        beq @rand_continue      ; 0 means 256 banks, keep going
        
        ; Normal case: check if we've passed the last bank
        lda reu_fill_bank
        cmp reu_banks
        beq @rand_continue      ; fill_bank == reu_banks: still need this bank
        bcc @rand_continue      ; fill_bank < reu_banks: more banks to go
        jmp @complete           ; fill_bank > reu_banks: done
        
@rand_continue:
        jmp @rand_fill_loop

; ---- Fast zero fill path (one DMA per 64KB bank) ----
@fast_zero_fill:
        ; Store a zero byte in a known location for the fixed-address DMA
        lda #0
        sta reu_zero_byte
        
@zero_bank_loop:
        ; Check for space bar to abort
        jsr getin
        cmp #$20
        bne @zero_not_aborted
        jmp @aborted
@zero_not_aborted:
        
        ; Set up DMA: fixed C64 address -> incrementing REU address
        ; C64 address: point to our zero byte
        lda #<reu_zero_byte
        sta $df02
        lda #>reu_zero_byte
        sta $df03
        
        ; REU address: start of current bank
        lda #0
        sta $df04               ; REU address low = 0
        sta $df05               ; REU address high = 0
        lda reu_fill_bank
        sta $df06               ; REU bank
        
        ; Transfer length: 0 = 64KB (entire bank)
        lda #0
        sta $df07               ; length low
        sta $df08               ; length high (0,0 = 65536 bytes)
        
        ; Address control: fix C64 address (bit 7), increment REU (bit 6=0)
        lda #$80
        sta $df0a
        
        ; Execute stash: the REC will read our single zero byte 65536 times
        ; while incrementing through the entire REU bank at ~1 byte/cycle
        lda #$90                ; stash with execute
        sta $df01
        
        ; Update KB counter: one bank = 64KB
        lda reu_kb_counter
        clc
        adc #64
        sta reu_kb_counter
        lda reu_kb_counter+1
        adc #0
        sta reu_kb_counter+1
        
        ; Show progress
        jsr show_fill_progress
        
        ; Next bank
        inc reu_fill_bank
        beq @complete           ; wrapped 255->0: all 256 banks done (16MB)
        
        ; For reu_banks=0 (256 banks), only the wrap above terminates
        lda reu_banks
        beq @zero_bank_cont     ; 0 means 256 banks, keep going
        
        ; Normal case: check if we've passed the last bank
        lda reu_fill_bank
        cmp reu_banks
        beq @zero_bank_cont     ; fill_bank == reu_banks: still need this bank
        bcc @zero_bank_cont     ; fill_bank < reu_banks: more banks to go
        jmp @complete           ; fill_bank > reu_banks: done
        
@zero_bank_cont:
        jmp @zero_bank_loop

@complete:
        ; Fill completed successfully
        clc                     ; carry clear = success
        rts
        
@aborted:
        ; User pressed space bar
        sec                     ; carry set = aborted
        rts

; =============================================================================
; show_fill_progress - display current KB / total KB progress
; =============================================================================
show_fill_progress:
        lda #$0d
        jsr chrout
        lda #<reu_progress_msg
        ldy #>reu_progress_msg
        jsr print_string
        
        lda reu_kb_counter
        sta zp_temp
        lda reu_kb_counter+1
        sta zp_temp+1
        jsr print_decimal_word
        
        lda #<reu_kb_of_msg
        ldy #>reu_kb_of_msg
        jsr print_string
        
        lda reu_size_kb
        sta zp_temp
        lda reu_size_kb+1
        sta zp_temp+1
        jsr print_decimal_word
        
        lda #<reu_kb_suffix2
        ldy #>reu_kb_suffix2
        jsr print_string
        rts

; Single zero byte for fixed-address DMA source
reu_zero_byte:
        !byte 0

; =============================================================================
; =============================================================================
; offer_save_reu_to_disk - prompt and save REU random data to disk
; Features:
;   - Prompts for drive number (default 8) and filename (default RNGFILL)
;   - Checks disk free blocks and whether file already exists
;   - If file exists: appends more random data until disk full
;   - If file doesn't exist: creates new sequential file
;   - If REU is smaller than disk: refills REU and continues writing
;   - Optimized write loop: checks I/O status once per 254-byte block
;     instead of per byte (~2x throughput vs per-byte status check)
; =============================================================================
offer_save_reu_to_disk:
        lda #<reu_save_prompt
        ldy #>reu_save_prompt
        jsr print_string
        
        jsr getin_wait
        cmp #'N'
        bne +
        jmp @no_save
+       cmp #'n'
        bne +
        jmp @no_save
+
        ; --- Prompt for drive number ---
        lda #<reu_drive_prompt
        ldy #>reu_drive_prompt
        jsr print_string
        
        jsr getin_wait
        cmp #$0d                ; Enter = default 8
        beq @use_drive_8
        cmp #'9'
        beq @use_drive_9
        cmp #'1'
        beq @use_drive_10p
        ; Default to 8 for anything else
@use_drive_8:
        lda #8
        jmp @store_drive
@use_drive_9:
        lda #9
        jmp @store_drive
@use_drive_10p:
        ; Might be 10 or 11 -- read next digit
        jsr getin_wait
        cmp #'0'
        beq @drive_10
        cmp #'1'
        beq @drive_11
        lda #8                  ; fallback
        jmp @store_drive
@drive_10:
        lda #10
        jmp @store_drive
@drive_11:
        lda #11
@store_drive:
        sta save_drive_num
        
        ; Echo drive number
        pha
        lda save_drive_num
        jsr print_byte_decimal
        lda #$0d
        jsr chrout
        pla
        
        ; --- Prompt for filename ---
        lda #<reu_filename_prompt
        ldy #>reu_filename_prompt
        jsr print_string
        
        jsr get_input_line
        
        ; Check if empty input - use default "RNGFILL"
        lda input_index
        bne @have_filename
        
        ldx #0
@copy_default:
        lda default_save_filename,x
        beq @default_done
        sta filename_buf,x
        inx
        jmp @copy_default
@default_done:
        stx input_index
        
@have_filename:
        ; Copy filename for reuse (save the clean name before we modify it)
        ldx #0
@save_name:
        lda filename_buf,x
        sta rng_save_filename,x
        inx
        cpx input_index
        bne @save_name
        lda #0
        sta rng_save_filename,x
        lda input_index
        sta rng_save_namelen
        
        ; Echo filename
        lda #<rng_save_filename
        ldy #>rng_save_filename
        jsr print_string
        lda #$0d
        jsr chrout
        
        ; --- Check disk free blocks ---
        lda #<reu_checking_disk_msg
        ldy #>reu_checking_disk_msg
        jsr print_string
        
        jsr get_disk_free_blocks
        bcc @have_free_info
        jmp @disk_error
        
@have_free_info:
        ; Display free blocks
        lda #<reu_free_blocks_msg
        ldy #>reu_free_blocks_msg
        jsr print_string
        
        lda disk_free_lo
        sta zp_temp
        lda disk_free_hi
        sta zp_temp+1
        jsr print_decimal_word
        
        lda #<reu_blocks_suffix
        ldy #>reu_blocks_suffix
        jsr print_string
        
        ; Check if any free space
        lda disk_free_lo
        ora disk_free_hi
        bne @have_space
        jmp @no_space
@have_space:
        
        ; --- Check if file already exists ---
        jsr rng_check_file
        lda rng_file_exists
        beq @create_new_file
        
        ; File exists - offer to append
        lda #<rng_file_exists_msg
        ldy #>rng_file_exists_msg
        jsr print_string
        
        lda #<rng_append_prompt
        ldy #>rng_append_prompt
        jsr print_string
        
        jsr getin_wait
        cmp #'N'
        bne +
        jmp @no_save
+       cmp #'n'
        bne +
        jmp @no_save
+
        ; Open for append
        jsr open_append_file
        bcc @file_open
        jmp @open_error
        
@create_new_file:
        jsr open_new_file
        bcc @file_open
        jmp @open_error
        
@file_open:
        ; --- Main write loop: write REU to disk, refilling as needed ---
        lda #0
        sta reu_read_bank
        sta reu_read_addr_hi
        sta blocks_written_lo
        sta blocks_written_hi
        sta rng_pass_num
        sta rng_reu_exhausted
        
        lda #<reu_writing_msg
        ldy #>reu_writing_msg
        jsr print_string
        
@write_main_loop:
        ; Check for space bar to abort
        jsr getin
        cmp #$20
        bne +
        jmp @write_aborted_close
+
        ; Check if disk free blocks exhausted
        lda blocks_written_hi
        cmp disk_free_hi
        bcc @still_space
        bne +
        lda blocks_written_lo
        cmp disk_free_lo
        bcc @still_space
+       jmp @write_complete
        
@still_space:
        ; Check if REU is exhausted (read through all banks)
        lda rng_reu_exhausted
        beq @reu_has_data
        
        ; REU exhausted — refill with random and reset read pointer
        inc rng_pass_num
        
        lda #$0d
        jsr chrout
        lda #<rng_refilling_msg
        ldy #>rng_refilling_msg
        jsr print_string
        
        lda rng_pass_num
        clc
        adc #1
        jsr print_byte_decimal
        lda #<rng_pass_suffix
        ldy #>rng_pass_suffix
        jsr print_string
        
        ; Close file temporarily during REU fill (long operation)
        jsr close_save_file
        
        ; Refill REU with fresh random data (silent - no prompts)
        lda #1
        sta reu_fill_random
        jsr refill_reu_core
        ; Ignore abort during refill - we still need to reopen and continue
        
        ; Reopen file for append
        jsr open_append_file
        bcc +
        jmp @open_error
+
        ; Reset REU read pointer
        lda #0
        sta reu_read_bank
        sta reu_read_addr_hi
        sta rng_reu_exhausted
        
        jmp @write_main_loop
        
@reu_has_data:
        ; Fetch 254 bytes from REU to C64 buffer
        jsr fetch_block_from_reu
        
        ; Write buffer to file (optimized: status check once per block)
        jsr write_block_to_file
        bcs @write_error_close
        
        ; Increment block counter
        inc blocks_written_lo
        bne @show_write_progress
        inc blocks_written_hi
        
@show_write_progress:
        ; Show progress every 16 blocks to reduce screen I/O overhead
        lda blocks_written_lo
        and #$0f
        bne @write_main_loop
        
        lda #$0d
        jsr chrout
        lda #<reu_progress_msg
        ldy #>reu_progress_msg
        jsr print_string
        
        lda blocks_written_lo
        sta zp_temp
        lda blocks_written_hi
        sta zp_temp+1
        jsr print_decimal_word
        
        lda #<reu_of_msg
        ldy #>reu_of_msg
        jsr print_string
        
        lda disk_free_lo
        sta zp_temp
        lda disk_free_hi
        sta zp_temp+1
        jsr print_decimal_word
        
        lda #<reu_blocks_suffix
        ldy #>reu_blocks_suffix
        jsr print_string
        
        jmp @write_main_loop
        
@write_complete:
        jsr close_save_file
        lda #$0d
        jsr chrout
        lda #<reu_save_done_msg
        ldy #>reu_save_done_msg
        jsr print_string
        
        ; Show total written
        lda blocks_written_lo
        sta zp_temp
        lda blocks_written_hi
        sta zp_temp+1
        jsr print_decimal_word
        lda #<rng_blocks_written_msg
        ldy #>rng_blocks_written_msg
        jsr print_string
        
@no_save:
        rts
        
@write_aborted_close:
        jsr close_save_file
        lda #$0d
        jsr chrout
        lda #<reu_write_aborted_msg
        ldy #>reu_write_aborted_msg
        jsr print_string
        rts

@write_error_close:
        jsr close_save_file
        lda #$0d
        jsr chrout
        lda #<reu_write_error_msg
        ldy #>reu_write_error_msg
        jsr print_string
        rts
        
@disk_error:
        lda #<reu_disk_error_msg
        ldy #>reu_disk_error_msg
        jsr print_string
        rts
        
@no_space:
        lda #<reu_no_space_msg
        ldy #>reu_no_space_msg
        jsr print_string
        rts
        
@open_error:
        lda #<reu_open_error_msg
        ldy #>reu_open_error_msg
        jsr print_string
        rts

; =============================================================================
; rng_check_file - check if rng_save_filename exists on disk
; Sets rng_file_exists: 0=no, 1=yes
; Opens file for reading, then checks drive error channel (#15)
; =============================================================================
rng_check_file:
        lda #0
        sta rng_file_exists
        
        ; Ensure clean state
        jsr clrchn
        lda #4
        jsr close
        lda #15
        jsr close
        
        ; Build "0:filename,s,r"
        lda #$30                ; '0'
        sta chk_fname_buf
        lda #$3a                ; ':'
        sta chk_fname_buf+1
        
        ldx #0
@copy_name:
        cpx rng_save_namelen
        beq @add_suffix
        lda rng_save_filename,x
        sta chk_fname_buf+2,x
        inx
        cpx #16
        bne @copy_name
        
@add_suffix:
        txa
        clc
        adc #2
        tay
        lda #','
        sta chk_fname_buf,y
        iny
        lda #'S'
        sta chk_fname_buf,y
        iny
        lda #','
        sta chk_fname_buf,y
        iny
        lda #'R'
        sta chk_fname_buf,y
        iny
        sty chk_fname_len
        
        ; Try to open file for reading
        lda chk_fname_len
        ldx #<chk_fname_buf
        ldy #>chk_fname_buf
        jsr setnam
        
        lda #4                  ; file number 4
        ldx save_drive_num
        ldy #4                  ; secondary address
        jsr setlfs
        
        jsr open
        bcs @not_found          ; KERNAL-level open failed
        
        ; Open command channel to check drive error status
        lda #0                  ; no filename for command channel
        ldx #<chk_fname_buf    ; dummy pointer (length 0 means ignored)
        ldy #>chk_fname_buf
        jsr setnam
        
        lda #15                 ; file number 15
        ldx save_drive_num
        ldy #15                 ; secondary address 15 = command channel
        jsr setlfs
        
        jsr open
        bcs @close_file_not_found
        
        ; Read error code from command channel
        ldx #15
        jsr chkin
        bcs @close_all_not_found
        
        ; Read first two characters (error number, e.g. "00" or "62")
        jsr chrin
        sta chk_err_tens
        jsr chrin
        sta chk_err_ones
        
        ; Close command channel
        jsr clrchn
        lda #15
        jsr close
        
        ; Close data file
        lda #4
        jsr close
        
        ; Check error code: "00" = OK (file found), anything else = not found
        lda chk_err_tens
        cmp #$30                ; '0'
        bne @not_found_clean
        lda chk_err_ones
        cmp #$30                ; '0'
        bne @not_found_clean
        
        ; File exists
        lda #1
        sta rng_file_exists
        rts
        
@close_all_not_found:
        jsr clrchn
        lda #15
        jsr close
@close_file_not_found:
        jsr clrchn
        lda #4
        jsr close
@not_found:
@not_found_clean:
        lda #0
        sta rng_file_exists
        rts

chk_fname_buf:
        !fill 32, 0
chk_fname_len:
        !byte 0
chk_err_tens:
        !byte 0
chk_err_ones:
        !byte 0

; =============================================================================
; open_new_file - open new sequential file for writing
; =============================================================================
open_new_file:
        ; Ensure clean I/O state
        jsr clrchn
        lda #2
        jsr close
        
        ; Build "0:filename,s,w"
        lda #$30                ; '0'
        sta write_fname_buf2
        lda #$3a                ; ':'
        sta write_fname_buf2+1
        
        ldx #0
@copy:
        cpx rng_save_namelen
        beq @add_suffix
        lda rng_save_filename,x
        sta write_fname_buf2+2,x
        inx
        cpx #16
        bne @copy
        
@add_suffix:
        txa
        clc
        adc #2
        tay
        lda #','
        sta write_fname_buf2,y
        iny
        lda #'S'
        sta write_fname_buf2,y
        iny
        lda #','
        sta write_fname_buf2,y
        iny
        lda #'W'
        sta write_fname_buf2,y
        iny
        sty write_fname_len2
        
        lda #2                  ; file number
        ldx save_drive_num
        ldy #2                  ; secondary address for write
        jsr setlfs
        
        lda write_fname_len2
        ldx #<write_fname_buf2
        ldy #>write_fname_buf2
        jsr setnam
        
        jsr open
        bcs @error
        
        ldx #2
        jsr chkout
        bcs @close_error
        
        clc
        rts
        
@close_error:
        lda #2
        jsr close
@error:
        sec
        rts

write_fname_buf2:
        !fill 32, 0
write_fname_len2:
        !byte 0

; =============================================================================
; open_append_file - open existing sequential file for append
; Uses DOS command "0:filename,s,a"
; =============================================================================
open_append_file:
        ; Ensure clean I/O state
        jsr clrchn
        lda #2
        jsr close
        
        ; Build "0:filename,s,a"
        lda #$30                ; '0'
        sta write_fname_buf2
        lda #$3a                ; ':'
        sta write_fname_buf2+1
        
        ldx #0
@copy:
        cpx rng_save_namelen
        beq @add_suffix
        lda rng_save_filename,x
        sta write_fname_buf2+2,x
        inx
        cpx #16
        bne @copy
        
@add_suffix:
        txa
        clc
        adc #2
        tay
        lda #','
        sta write_fname_buf2,y
        iny
        lda #'S'
        sta write_fname_buf2,y
        iny
        lda #','
        sta write_fname_buf2,y
        iny
        lda #'A'                ; Append mode
        sta write_fname_buf2,y
        iny
        sty write_fname_len2
        
        lda #2                  ; file number
        ldx save_drive_num
        ldy #2                  ; secondary address
        jsr setlfs
        
        lda write_fname_len2
        ldx #<write_fname_buf2
        ldy #>write_fname_buf2
        jsr setnam
        
        jsr open
        bcs @error
        
        ldx #2
        jsr chkout
        bcs @close_error
        
        clc
        rts
        
@close_error:
        lda #2
        jsr close
@error:
        sec
        rts

; =============================================================================
; print_byte_decimal - print A as 1-3 digit decimal number
; =============================================================================
print_byte_decimal:
        sta pb_val
        lda #0
        sta pb_leading
        
        ; Hundreds
        ldx #0
        lda pb_val
@hundreds:
        cmp #100
        bcc @tens
        sec
        sbc #100
        inx
        jmp @hundreds
@tens:
        sta pb_val
        cpx #0
        beq @skip_hundreds
        txa
        clc
        adc #'0'
        jsr chrout
        lda #1
        sta pb_leading
@skip_hundreds:
        
        ; Tens
        ldx #0
        lda pb_val
@tens_loop:
        cmp #10
        bcc @ones
        sec
        sbc #10
        inx
        jmp @tens_loop
@ones:
        sta pb_val
        cpx #0
        bne @print_tens
        lda pb_leading
        beq @skip_tens
@print_tens:
        txa
        clc
        adc #'0'
        jsr chrout
@skip_tens:
        
        ; Ones (always print)
        lda pb_val
        clc
        adc #'0'
        jsr chrout
        rts

pb_val:     !byte 0
pb_leading: !byte 0

; =============================================================================
; get_disk_free_blocks - read directory to get free blocks
; Robust version: clears channels, closes stale handles before starting
; =============================================================================
get_disk_free_blocks:
        ; Ensure clean KERNAL I/O state
        jsr clrchn
        
        ; Close any stale file #1 (ignore errors)
        lda #1
        jsr close
        
        ; Open directory
        lda #1                  ; file number
        ldx save_drive_num
        ldy #0                  ; secondary address
        jsr setlfs
        
        lda #1
        ldx #<dir_name
        ldy #>dir_name
        jsr setnam
        
        jsr open
        bcs @error
        
        ldx #1
        jsr chkin
        bcs @close_error
        
        ; Skip first two bytes (load address)
        jsr chrin
        jsr chrin
        
        ; Read directory lines
        ; Format: link_lo, link_hi, blk_lo, blk_hi, text..., $00
        ; Last useful line is "BLOCKS FREE" whose block count = free blocks
@read_loop:
        ; Read link bytes
        jsr chrin
        sta dir_link_lo
        jsr readst
        and #$40
        bne @use_last           ; EOF before we got link = use last count
        
        jsr chrin
        sta dir_link_hi
        jsr readst
        and #$40
        bne @use_last
        
        ; Read block count (16-bit little-endian line number)
        jsr chrin
        sta disk_free_lo        ; overwrite each time; final = free blocks
        jsr readst
        and #$40
        bne @use_last
        
        jsr chrin
        sta disk_free_hi
        jsr readst
        and #$40
        bne @use_last
        
        ; Skip rest of line until null terminator
@skip_line:
        jsr chrin
        pha
        jsr readst
        and #$40
        bne @eof_in_line
        pla
        cmp #0
        bne @skip_line
        jmp @read_loop
        
@eof_in_line:
        pla                     ; discard stacked byte

@use_last:
        ; disk_free_lo/hi holds the last line's block count = free blocks
        jsr clrchn
        lda #1
        jsr close
        clc
        rts
        
@close_error:
        jsr clrchn
        lda #1
        jsr close
@error:
        sec
        rts

dir_name:
        !text "$"

dir_link_lo:
        !byte 0
dir_link_hi:
        !byte 0

; =============================================================================
; close_save_file - close the output file and clear channel
; =============================================================================
close_save_file:
        jsr clrchn
        lda #2
        jsr close
        rts

; =============================================================================
; fetch_block_from_reu - DMA fetch 254 bytes from REU to buffer
; Sets rng_reu_exhausted=1 when all banks have been read
; =============================================================================
fetch_block_from_reu:
        ; Set up DMA transfer
        lda #<reu_zero_buffer
        sta $df02               ; C64 address low
        lda #>reu_zero_buffer
        sta $df03               ; C64 address high
        
        lda #0
        sta $df04               ; REU address low
        lda reu_read_addr_hi
        sta $df05               ; REU address high
        lda reu_read_bank
        sta $df06               ; REU bank
        
        lda #254                ; block size (1541 sector data = 254 bytes)
        sta $df07
        lda #0
        sta $df08
        sta $df0a               ; increment both addresses
        
        lda #$91                ; fetch with execute
        sta $df01
        
        ; Advance REU read pointer by one page (256 bytes, wastes 2)
        inc reu_read_addr_hi
        bne @no_bank_wrap
        
        ; Wrapped past end of bank
        inc reu_read_bank
        beq @reu_done           ; wrapped 255->0: all 256 banks read (16MB)
        
        ; For reu_banks=0 (256 banks), only the wrap above exhausts
        lda reu_banks
        beq @no_bank_wrap       ; 0 means 256 banks, keep going
        
        ; Normal case: check if we've read past the last bank
        lda reu_read_bank
        cmp reu_banks
        beq @no_bank_wrap       ; read_bank == reu_banks: still valid
        bcc @no_bank_wrap       ; read_bank < reu_banks: still valid
        
@reu_done:
        ; REU exhausted
        lda #1
        sta rng_reu_exhausted
        
@no_bank_wrap:
        rts

; =============================================================================
; write_block_to_file - write 254 bytes from buffer to file
; Status check: only bit 7 (device not present) is fatal.
; Bits 0/1 (serial bus timeout) are transient — KERNAL chrout handles
; retries internally. These bits accumulate across the 254 chrout calls
; and will eventually trigger false errors during extended writes,
; especially on 1581 which has variable seek times.
; =============================================================================
write_block_to_file:
        ldx #2                  ; reselect output channel
        jsr chkout
        bcs @error
        
        ldx #0
@write_byte:
        lda reu_zero_buffer,x
        jsr chrout
        inx
        cpx #254
        bne @write_byte
        
        ; Check status — only device-not-present is fatal
        jsr readst
        and #$80                ; bit 7 only: device not present
        bne @error
        
        clc
        rts
        
@error:
        sec
        rts

; Variables for disk save
save_drive_num:
        !byte 8
disk_free_lo:
        !byte 0
disk_free_hi:
        !byte 0
blocks_written_lo:
        !byte 0
blocks_written_hi:
        !byte 0
reu_read_bank:
        !byte 0
reu_read_addr_hi:
        !byte 0
rng_file_exists:
        !byte 0
rng_reu_exhausted:
        !byte 0
rng_pass_num:
        !byte 0
rng_save_namelen:
        !byte 0
rng_save_filename:
        !fill 18, 0

default_save_filename:
        !text "RNGFILL"
        !byte 0

; =============================================================================
; prepare_fill_buffer - fill 256-byte buffer with zeros or random
; Buffer size of 256 bytes is optimal: DMA setup overhead is ~30 cycles
; per stash vs ~100 cycles/byte for PRNG generation, so DMA cost is <2%
; regardless of buffer size. 256 bytes also aligns with REU page size.
; =============================================================================
prepare_fill_buffer:
        lda reu_fill_random
        bne @random_fill
        
        ; Zero fill
        ldx #0
        lda #0
@zero_loop:
        sta reu_zero_buffer,x
        inx
        bne @zero_loop
        rts
        
@random_fill:
        ; Random fill using PRNG - optimized loop
        ; lfsr_random returns byte in A, doesn't need X preserved
        lda #0
        sta fill_buf_idx
@random_loop:
        jsr lfsr_random         ; returns random byte in A
        ldx fill_buf_idx
        sta reu_zero_buffer,x
        inc fill_buf_idx
        bne @random_loop
        rts

fill_buf_idx:
        !byte 0

; Variables for REU fill
reu_fill_bank:
        !byte 0
reu_fill_addr_hi:
        !byte 0
reu_total_banks:
        !byte 0
reu_fill_random:
        !byte 0
reu_kb_counter:
        !word 0

; 256-byte buffer for REU operations
reu_zero_buffer:
        !fill 256, 0

; =============================================================================
; getin_wait - wait for a keypress
; =============================================================================
getin_wait:
        jsr getin
        cmp #0
        beq getin_wait
        rts

